replicaCount: 2

image:
  repository: cloudwranglers/website
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: cloudwranglers.io
  path: /
  tls:
    enabled: true
    secretName: cloudwranglers-tls

certManager:
  email: info@cloudwranglers.io
  staging: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80 