{{- if .Values.loadBalancer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudwranglers.fullname" . }}-lb
  namespace: {{ include "cloudwranglers.namespace" . }}
  labels:
    {{- include "cloudwranglers.labels" . | nindent 4 }}
    service-type: loadbalancer
  {{- with .Values.loadBalancer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.loadBalancer.type }}
  {{- if .Values.loadBalancer.loadBalancerIP }}
  loadBalancerIP: {{ .Values.loadBalancer.loadBalancerIP }}
  {{- end }}
  {{- if .Values.loadBalancer.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.loadBalancer.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.loadBalancer.port }}
      targetPort: {{ .Values.loadBalancer.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "cloudwranglers.selectorLabels" . | nindent 4 }}
{{- end }}