apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudwranglers.fullname" . }}
  namespace: {{ include "cloudwranglers.namespace" . }}
  labels:
    {{- include "cloudwranglers.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "cloudwranglers.selectorLabels" . | nindent 4 }} 