{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudwranglers.serviceAccountName" . }}
  namespace: {{ include "cloudwranglers.namespace" . }}
  labels:
    {{- include "cloudwranglers.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}